# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Template-Extension
version:      0.26
version_from: Extension.pm
installdirs:  site
requires:
    HTML::Parser:                  0
    HTML::Template:                2.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
